### ISSUE TITLE
Document python/pip versions a bit more

### ISSUE THREAD

**Issue by greggles** [kibaffo33/aws_transcribe_to_docx#9]
I had a pretty fresh MacOS Catalina machine and tried installing this by doing:

```
brew install pip
pip install tscribe
```

I got an error saying pip couldn't find the tscribe package. I also got a lot of warnings from pip about using python2 that ships with catalina.

I then decided to look into my python versions and after installing python 3.8 and pip 19.2.3 my call to `pip install tscribe` succeeded.

I'm not a really strong python developer/user and I'm not sure if I solved the problem the right way. It seems like it could be good to specify more about the python environment from a base OS install in case this package is the first one someone is trying to install.

**Comment by kibaffo33** [comment]
Hi @greggles,

You solved it! Sounds like your first try was pip installing from Python 2. Python 2 reached end of life in Jan 2020, but still ships with many operating systems. Installing 3.8 was the right thing to do, brining your environment up to date. 

`tscribe` won't work with `2.x` due to use of things like 'f-strings'. 

The PyPI page shows support for `3.6`, `3.7` and `3.8`. Commit 70bf3c732ede14338e33621e0f45e8df80b80079 adds this as a badge on the readme.

Good luck with your project!

**Comment by greggles** [comment]
That's perfect, thanks!
